version: '3.7'

services:

  iris:
    depends_on:
      - plc
    hostname: iris
    init: true
    image: intersystemsdc/irisdemo-demo-opcua:iris-version-0.3.0
    ports:
    - "51793:51773" # 51773 is the superserver default port
    - "52783:52773" # 52773 is the webserver/management portal port

  plc:
    hostname: plc
    init: true
    image: intersystemsdc/opcua-mockserver:version-0.3.0
    ports:
    - "10000:4840"     # opc.tcp
    volumes:
    - type: bind
      source: ./mocksvr-data/
      target: /app/data
  
    
  certified-server:
    hostname: certified-server
    init: true
    image: intersystemsdc/irisdemo-demo-opcua:server-ctt-version-0.3.0
    ports:
    - "10001:4840"     # opc.tcp
  
    
  